version: "2"

services:
  addData:
    container_name: d-lambda
    image: lambci/lambda:nodejs12.x
    volumes:
      - .:/var/task
    ports:
      - 9001:9001
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      DOCKER_LAMBDA_STAY_OPEN: 1
    command: index.handler

networks:
  default:
    external:
      name: minio-lambda-net